import type { NextPage } from 'next'
import tw from 'twin.macro'
import styled from 'styled-components'

const Home: NextPage = () => {
  return (
    <MainDiv>
      <head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>

      <Card>
        <img
          src='https://tailwindcss.com/img/card-top.jpg'
          alt='Sunset in the mountains'
        />
        <CardInfo>
          <CardText>Next + Tailwind + Styled Components ❤️</CardText>
          <p>
            Next and Tailwind CSS are a match made in heaven, check out this
            article on how you can combine these two for your next app.
          </p>
        </CardInfo>
      </Card>
    </MainDiv>
  )
}

const MainDiv = tw.div`flex min-h-screen justify-center items-center`

const Card = styled.div`
  ${tw`max-w-xs rounded overflow-hidden shadow-lg my-2`};

  img {
    ${tw`w-full`};
  }

  p {
    ${tw`text-gray-500 text-base`};
  }
`

const CardInfo = tw.div`px-6 py-4`

const CardText = tw.div`font-bold text-xl mb-2`

export default Home
